### PR TITLE
Fixed data race when stopping server

### PR DESCRIPTION
**Pull request by jaspervandeven**
This should address (at least part of) the issue: Race condition between listen and stop, fortify failure #160

### CODE REVIEW

**Comment by yhirose** [comment]
@jaspervandeven, thanks for the PR. Could you take a look at unit test failures on the AppVeyor and Travis CI? Both CIs are reporting the same errors.

**Comment by jaspervandeven** [comment]
@yhirose, I am not able to recreatethe failing tests on my local system. Just running the test using make does not produce any error for me. As the information provided by the two CI servers is rather limited, I can not figure out, what the issue might be. I tried to use locks to make absolutly sure, no critical access to the svr_sock_ variable is possible, but still the CI's complain. Without a clear specification of the development environment, I am not able to look into this any further, sorry.

________________________________
Von: yhirose <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 14:35
An: yhirose/cpp-httplib
Cc: van de Ven, Jasper - ENCOWAY; Mention
Betreff: Re: [yhirose/cpp-httplib] Fixed data race when stopping server (#167)


@jaspervandeven<https://github.com/jaspervandeven>, thanks for the PR. Could you take a look at unit test failures on the AppVeyor and Travis CI? Both CIs are reporting the same errors.

-

**Comment by yhirose** [comment]
@jaspervandeven, thanks for checking the build issue on the CI servers. I pulled the PR on my MacBook and confirmed that the same problem is happening. It seems like `Server::listen_internal()` always fails now.

**Comment by jaspervandeven** [comment]
@yhirose, thats sad to read. However, without detailed information about the respective environmentes, I cannot continue to work on this error. I would require specific details regarding operating system (including version), compiler (including version), zlib version, and openssl version. I have it all running on an Ubuntu 18.04 with clang-6, libssl-dev 1.1.1, and zlib1g-dev 1:1.2.11 (and all according dependencies). The only thing I can think of to help further, is to create a docker developent environment, so that I can be sure, I am working on the same setup as the CI systems.

________________________________
Von: yhirose <notifications@github.com>
Gesendet: Freitag, 14. Juni 2019 01:47
An: yhirose/cpp-httplib
Cc: van de Ven, Jasper - ENCOWAY; Mention
Betreff: Re: [yhirose/cpp-httplib] Fixed data race when stopping server (#167)


@jaspervandeven<https://github.com/jaspervandeven>, thanks for checking the build issue on the CI servers. I pulled the PR on my MacBook and confirmed that the same problem is happening. It seems like Server::listen_internal() always fails now.

-

**Comment by jaspervandeven** [comment]
At the moment, I seem not to be able to build on the CI environments and its specifics are not available to me.

**Comment by yhirose** [comment]
@jaspervandeven, yes, I understand that supporting multi-platforms and multi-compilers require much more efforts than we expect... But at least, I was able to get an idea to fix the race condition issue from your change. Thanks for your taking time for it!

**Comment by jaspervandeven** [comment]
@yhirose, thanks for all the work on this cool library. Unfortunately, I still encounter a data race, when testing my code. I did also a little bit more research on the use of atomics, and came up with a further solution. Before I now throw that against your ci-servers, I wanted to ask, if you would like to test it locally on your machine without having a pull request which only exists to test on your server? I attached the changed library file (based on the most recent version from your github - one three to four lines of code should be effected). Hope it runs on windows or mac this time.

All the best, and again, thanks for all your outstanding work and effort.

Best, Jasper

________________________________
Von: yhirose <notifications@github.com>
Gesendet: Freitag, 14. Juni 2019 14:30
An: yhirose/cpp-httplib
Cc: van de Ven, Jasper - ENCOWAY; Mention
Betreff: Re: [yhirose/cpp-httplib] Fixed data race when stopping server (#167)


@jaspervandeven<https://github.com/jaspervandeven>, yes, I understand that supporting multi-platforms and multi-compilers require much more efforts than we expect... But at least, I was able to get an idea to fix the race condition issue from your change. Thanks for your taking time for it!

-

**Comment by yhirose** [comment]
@jaspervandeven, thanks for the further investigation on this matter. If your new change affects only a few lines of the code, you don't mind sending the pull request. Even if the CI servers might complain, I'll try to build and debug on my Windows and Mac OS machines.

**Comment by jaspervandeven** [comment]
@yhirose, I just found the time, to re-open the pull request with my last changes. One of the continuous-integration servers passes, one fails during SSL-checks, it seems. I did not change anything with regard to SSL. Hope, it makes sens to you. And if it makes its way into the library, I would be thrilled.

Best Jasper.

________________________________
Von: yhirose <notifications@github.com>
Gesendet: Freitag, 28. Juni 2019 16:11
An: yhirose/cpp-httplib
Cc: van de Ven, Jasper - ENCOWAY; Mention
Betreff: Re: [yhirose/cpp-httplib] Fixed data race when stopping server (#167)


@jaspervandeven<https://github.com/jaspervandeven>, thanks for the further investigation on this matter. If your new change affects only a few lines of the code, you don't mind sending the pull request. Even if the CI servers might complain, I'll try to build and debug on my Windows and Mac OS machines.

-

**Pull request closed without merging**
