### PR TITLE
Chunked transfer handlers for client

### PR DESCRIPTION
**Pull request by PixlRainbow**

### CODE REVIEW

**Comment by PixlRainbow** [comment]
I have just realized that process_request only checks the Request object for user-defined stream handlers very late in the processing, after it has already done reading from the incoming stream. This makes it difficult to implement chunked handlers for _incoming_ chunks without doing a major refactor

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the pull request! As you may have already noticed, I have been actually pondering over good user interface of the chunked transfer encoding support on client as well as other similar data transfer scenarios at #139. I'll try to understand your implementation and learn idea from it. Thanks for your efforts.

**Comment by yhirose** [comment]
@PixlRainbow, I have just fixed and closed #139. I learned a lot from your pull request to know how to implement the chunked transfer handler effectively. Thanks for your contribution!

**Comment by PixlRainbow** [comment]
No problem! Glad I could help. Just a pity that I have just found I cannot make use of this because neither Chrome not Firefox support streamed upload callbacks in JavaScript yet, even though it is in ES6 specifications.

**Pull request closed without merging**
