### PR TITLE
std::chrono::duration for timeout

### PR DESCRIPTION
**Pull request by ShirokovMikhail**
Now it is possible to use
`cli.set_read_timeout(500ms);`
if using c++14

### CODE REVIEW

**Comment by yhirose** [comment]
@ShirokovMikhail, thank you for the pull request. It looks very good. But it will break users' code, since the new API isn't compatible with the existing API... So I am not going to merge it to the master for now, but keep this pull request in mind for the future. Thank you very much for your contribution!

**Comment by ShirokovMikhail** [comment]
How about keeping both API options?

**Comment by yhirose** [comment]
Honestly, I am satisfied with the existing API with no problem, even if this suggestion is a bit more expressive.

**Comment by yhirose** [comment]
@ShirokovMikhail, I actually implemented your suggestion to have both interfaces with minimal changes at #891. Does it satisfy your needs?

**Comment by ShirokovMikhail** [comment]
@yhirose Great! Thanks a lot.

**Pull request closed without merging**
