### PR TITLE
Added progress to POST, PUT, PATCH and DELETE requests

### LINKED ISSUE #1330: httplib::Progress for Post requests?
Hello,
have you thought about adding a httplib::Progress for the "Post" requests ?

ty

### PR DESCRIPTION
**Pull request by rndm13**
Added multiple methods to Client and ClientImpl classes that accept progress callback for POST, PUT, PATCH and DELETE.
Needed to have a functionality for user to cancel their requests and these changes add that.
Main change is in send_with_content_provider which now also accepts Progress. Other changes are mostly boilerplate functions additions.
Fixes #1330 issue as well

### CODE REVIEW

**Comment by yhirose** [comment]
@rndm13, thanks for the pull request. Could you please add unit tests for the new methods?

**Comment by yhirose** [comment]
@rndm13, thanks for the contribution!

**Comment by kunlinyu** [comment]
@rndm13 HI, I am using this feature for "PUT"
```cpp
httplib::Client cli(domain);
auto res = cli.Put(
    path_with_params, {}, buffer.data(), bytes_read,
    "application/octet-stream", [&](uint64_t current, uint64_t total) {
      std::cout << "current/total: " << current << "/" << total << std::endl;
      return true;
    });
```

But even if I put a big file more then 10MB, the progress will always be "current/total: 16/16".
Then I check the code. I notice that the "read_content_with_length()" will call the progress lambda.

So I want to ask, is it about the progress of the file I put to the server, or the progress about the response?

**Comment by rndm13** [comment]
@kunlinyu Hello, from what I understand the progress does indeed give you information about server response, not about your client request.
Maybe it would be best to rename Progress to ResponseProgress to avoid this kind of confusion?

**Comment by kunlinyu** [comment]
@rndm13 Thank you! I think you are right. 
Accually the first time when I saw the name "progress", I thought it is response progress for GET and request progress for PUT and POST. It is very good to rename it ResponseProgress. And furthur more, I think we need both RequestProgress and ResponseProgress.

**Pull request merged**
