### PR TITLE
Added Client "Transfer-Encoding:Chunked" support when your content length is unpredictable.

### PR DESCRIPTION
**Pull request by berkanuslu**
When you're working with streams, especially if different threads control this stream, you might not know content-length, but you can transfer your data with Transfer-Encoding: Chunked. It has been implemented based on https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html documentation. I have created an example for transferring your data with chunked.

### CODE REVIEW

**Comment by yhirose** [comment]
@berkanuslu, thanks for the new pull request. But it looks same as before...

> Hi @berkanuslu, Im working with your code. It works ok but have some bugs:
Content-Length is included but chunked enconding conflict with it.
gzip compresion do not work, at least in my code. The code should be very similar to the server one. It will be great if some code can be reused in server and client.
>
> I dont know if you are working in the code or not. If the PR is enough for your needs i can continue your work.

**Comment by berkanuslu** [comment]
I didn't encounter any issue about gzip and content length conflict. @evg82, can you share any sample about that? Where did you find this problem? Because I think that gzip is about Content-Encoding, and chunked is about Transfer-Encoding. But please correct me if I'm wrong.

**Comment by evg82** [comment]
Im going to test your last pull, to see if i find any problem with compression.

**Comment by evg82** [comment]
Im testing it and see some problems:

You set in lines around 4960 "Transfer-Encoding: chunked" and "Content-Length: 0". However this headers are exclusive as i can read in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

I cant make compression works. In client when i enable compresion and send a post request, for example, and empty request is send. Im working in an example to test this problem.

**Comment by berkanuslu** [comment]
@evg82 you're right. I shouldn't force to set the Content-Length variable.  I have made some changes. I have tried with `cli.compress(true);` options, and there is no error now. Can you check the latest changes? If there is any problem, please let me know.

**Comment by evg82** [comment]
It work correctly on my machine

**Comment by yhirose** [comment]
@berkanuslu, I took a look at the code quickly, but I feel I cannot accept this pull request.

First of all, it doesn't support compression. If `cli.set_compress(true);` is enabled, then your unit test fails...

The chunked-encoding shouldn't be handled in `ClientImpl::write_request`, but `ClientImpl::send_with_content_provider` where we can handle both chunked-encoding and compression properly.

On server side, I have already implemented chunked-encoding with compression in `Server::write_content_with_provider` and `write_content_chunked`, and I think we can use the code as much as possible for the client implementation. In this way, we can avoid code duplication and handle chunked-encoding with compression properly.

As for content provider interface, `ContentProviderWithoutLength` needs to be used instead of `ContentProvider`, because `length` doesn't mean anything for the chunked-encoding. You can see how it is used on the server side.
https://github.com/yhirose/cpp-httplib/blob/9c7d841b37b69cde4ffb7c6d5c1aae6d5d6e1d97/httplib.h#L334-L335

Sorry for bringing up the above issues. But I really appreciate you pull request, because it gives me a motivation to support this feature.

Thanks!

**Comment by berkanuslu** [comment]
@yhirose Anyway, it's up to you. If you want to add this feature to the client implementation, I'll be happy with that.

**Pull request closed without merging**
