### PR TITLE
Add {Client,Client2}::set_decompress

### PR DESCRIPTION
**Pull request by vvanelslande**
I need the compressed body.

### CODE REVIEW

**Comment by yhirose** [comment]
@vvanelslande, the change looks good to me except one place. Could you make sure the `decompress_` is copied in `copy_settings`? Also could you add a simple unit test in test/test.cc?

https://github.com/yhirose/cpp-httplib/blob/63a96aeb20d8e1ec6d35655f91083cb3f1c26a89/httplib.h#L784

**Comment by vvanelslande** [comment]
1. done
2. no

**Comment by yhirose** [comment]
@vvanelslande, it seems like the unit test on GitHub Action fails... After you fix this failure and add a unit test for `set_decompress `, then I'll merge it right away. Thanks!

**Comment by vvanelslande** [comment]
idk why it fails

**Comment by yhirose** [comment]
@vvanelslande, when you are still interested in the pull request, please fix the problem and add a simple unit test case as I always ask contributors. I'll close it for now until then. Thank you for your efforts!

**Pull request closed without merging**
