### PR TITLE
client certificates support

### PR DESCRIPTION
**Pull request by PixlRainbow**
#154

### CODE REVIEW

**Comment by yhirose** [comment]
@PixlRainbow, thank you so much for the fine contribution! I'll review the code when I am not busy.

Meanwhile, could you add at least two unit test cases ('success' and 'failure' cases) in text.cc, so that we can make sure that other contributors won't break the code accidentally? There are already test cases for server certificate check at the bottom of test.cc. So you can add them after that.

Only think so far in the code is about the usage of `SSL_CTX_load_verify_locations`. According to [the OpenSSL API reference](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html), both `CAfile` and `CApath` are not required when calling the API. It's ok if either one is specified. So I think the sentences like `if(trusted_cert_path && client_cert_path)` should be `if(trusted_cert_path || client_cert_path)`. I found the similar code pattern in curl at [here]( https://github.com/curl/curl/blob/8986d3c6f4f72cb4734f24ef297d31865e3018cc/lib/vtls/openssl.c#L2605-L2608)

Thanks a lot!

**Comment by PixlRainbow** [comment]
@yhirose although `CApath` is optional (for self-signed client certificates), `CAfile` is actually needed in this case because although `SSL_CTX_load_verify_locations` can accept having either one, `SSL_load_client_CA_file` absolutely requires a file and not a directory.
The former loads certificates and builds the chain of trust locally while the latter is the list of acceptable CAs to be requested from the client.

**Comment by PixlRainbow** [comment]
I have found the reason why my tests were failing with desktop Chrome and Firefox with CA-signed certificates. I was testing with the wrong certificate. I took a closer look at the [OpenSSL API reference](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_CA_list.html#NOTES) and realized I should be using the _CA's_ certificate as `client_cert_path` and not the client's public key.
The reason why my wrong test configuration worked with self-signed client certificates is because such certificates serve as root CAs and client public keys in one.

**Comment by PixlRainbow** [comment]
it appears the build failed on Travis CI because c_rehash was removed from Mac OS X starting with High Sierra

**Comment by PixlRainbow** [comment]
@yhirose you mind initiating a rebuild on AppVeyor? I did not change anything between b2f4120 and 2d532a6 that would have caused _just_ the Windows build to fail on that particular test.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for adding the test cases. I kicked the PR build again. Interestingly, my first and second attempts failed, but the third attempt succeeded.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for adding the test cases. I kicked the PR build again. The first and second attempts failed like you experienced, but the third attempt finally succeeded. It's really interesting, but good news anyway.

**Comment by PixlRainbow** [comment]
might have just been that particular cloud instance being too busy to serve packets or dropping packets

**Comment by PixlRainbow** [comment]
@yhirose I am considering adding the X509's name field to `Request` so that request handlers of `SSLServer` are able to identify multiple specific users. The name is obtained by getting X509 pointer with `SSL_get_peer_certificate(const SSL *s)` and then accessing the `char* name` member of the X509. However, `Request req` is constructed within the scope of `Server::process_request` so `SSLServer` cannot access `req` by calling the inherited function.
**I can think of two ways**
1. Modify `Server::process_request` to take `Request &req` as a parameter like `Client::process_request` so that `SSLServer` can attach a cert name to the `req` before passing to inherited function.
2. Copy and paste the entire contents of `Server::process_request` into `SSLServer::process_request`, then adding one line before the `routing` call to add certificate name to `req`.

I am asking for your suggestion or opinion because I am afraid of making changes that you might consider too drastic and I am uncertain if you have intentionally sandboxed the Request within the base `Server` class for security reasons.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the great contribution!

**Pull request merged**
