### PR TITLE
Pass certs and keys from memory

### PR DESCRIPTION
**Pull request by ottigeda**
I would like to be able to pass certificates and keys from memory to the SSLServer and SSLClient, rather than using them from files on disk.
Therefore I did the modifications to allow this.
I hope you could have a look at it add this to your really cool library ?
I did run your test-cases and everything seems to be fine.

### CODE REVIEW

**Comment by yhirose** [comment]
@ottigeda, thank you for your contribution! I only accepts pull requests with corresponding unit tests in test/test.cc. Could you add a unit test for the pull request? You can refer to my test cases for the file based certificate and key there. Thank you!

**Comment by ottigeda** [comment]
Makes lot of sense, just added an test case.
Do you think it is fine now ?

**Comment by yhirose** [comment]
@ottigeda, excellent! The code looks very good to me. Thanks for your find contribution!

**Comment by ottigeda** [comment]
Thanks a lot, happy you like my contribution!
Was the 1st pull request I did :-)

**Pull request merged**
