### PR TITLE
added server streamhandler to handle large post data. 

### PR DESCRIPTION
**Pull request by sophana**
It is now possible to register a stream handler which has access to the request stream.
The handler is able to call read_content on the stream with its own handler.
Updated simplesvr example

### CODE REVIEW

**Comment by PixlRainbow** [comment]
referenced PR: #242

**Comment by PixlRainbow** [comment]
Could you not have simply re-used the existing `httplib::detail::ContentReceiver` instead of creating a new type?

**Comment by yhirose** [comment]
@sophana, thanks for your contribution. I just took a look at your code, but I cannot accept this PR. It is because the fix exposes `Stream` and user code needs to call `detail::read_content`. Both are 'internal' items which are not supposed to be used by users.

But I understand what you are trying to do with the PR and it's useful for large data. I'll implement this feature when I have time. Thanks for bringing up this matter!

**Comment by sophana** [comment]
You may want to hide read_content and stream by providing a binded version of read_content in the handlers arguments?

**Pull request closed without merging**
