### PR TITLE
Avoid copying of content provider if possible

### PR DESCRIPTION
**Pull request by Fefer-Ivan**
Right now all content providers are copied inside set_content_provider or set_chunked_content_provider calls.
I replaced explicit copying in capture with move, so it should avoid coping when possible.

Because I can't move-capture in C++11, I had to create ContentProviderAdapter class explicitly.

### CODE REVIEW

**Comment by yhirose** [comment]
@Fefer-Ivan, thanks for the pull request. The code looks very good to me. Could you add a unit test which cannot be compiled with the old httplib.h? (The test case doesn't need to have any test assertion.) Thanks!

**Comment by Fefer-Ivan** [comment]
@yhirose, I would love to, but even after this changes, I can't pass move-only object as ContentProvider (aka std::function<bool(size_t offset, size_t length, DataSink &sink)>) because std::function requires it to be copyable: https://en.cppreference.com/w/cpp/utility/functional/function/function: `F must meet the requirements of Callable and CopyConstructible.`

I can add a test with a class, that throws an exception in copy constructor or counts the number of times copy constructor is called and asserts that it is zero in destructor, but neither option seems good to me.

**Comment by yhirose** [comment]
> I would love to, but even after this changes, I can't pass move-only object as ContentProvider 

@Fefer-Ivan, does it mean that the changes in this pull request are not enough to accomplish your intention?

**Comment by Fefer-Ivan** [comment]
@yhirose, yes, this changes are more like performance optimization, which is still looks good, so I decided to create a pull request.

**Comment by yhirose** [comment]
@Fefer-Ivan, thanks for the clear explanation. (I thought this PR is directly for #624.) I think a unit test is not needed. Thanks!

**Pull request merged**
