### PR TITLE
Use gen-certs.sh for cmake as well

### LINKED ISSUE #1798: `SSLClientServerTest.*` tests fail with OpenSSL 3.2.1
When attempting to run the test suite on Gentoo Linux amd64, I'm seeing most of the `SSLClientServerTest.*` tests fail:

```
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] SSLClientServerTest.ClientCertPresent
[  FAILED  ] SSLClientServerTest.ClientEncryptedCertPresent
[  FAILED  ] SSLClientServerTest.MemoryClientCertPresent
[  FAILED  ] SSLClientServerTest.MemoryClientEncryptedCertPresent
[  FAILED  ] SSLClientServerTest.TrustDirOptional
[  FAILED  ] SSLClientServerTest.CustomizeServerSSLCtx
```

This is on 548dfff0aef25e36e971af96b49ce7fbb72d840e (but I also reproduce the same result on 0.15.3).

Detailed results:

```
[----------] 8 tests from SSLClientServerTest
[ RUN      ] SSLClientServerTest.ClientCertPresent
test.cc:5160: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.ClientCertPresent (7 ms)
[ RUN      ] SSLClientServerTest.ClientEncryptedCertPresent
test.cc:5160: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.ClientEncryptedCertPresent (7 ms)
[ RUN      ] SSLClientServerTest.MemoryClientCertPresent
test.cc:5243: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.MemoryClientCertPresent (6 ms)
[ RUN      ] SSLClientServerTest.MemoryClientEncryptedCertPresent
test.cc:5243: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.MemoryClientEncryptedCertPresent (7 ms)
[ RUN      ] SSLClientServerTest.ClientCertMissing
[       OK ] SSLClientServerTest.ClientCertMissing (5 ms)
[ RUN      ] SSLClientServerTest.TrustDirOptional
test.cc:5308: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.TrustDirOptional (6 ms)
[ RUN      ] SSLClientServerTest.SSLConnectTimeout
[       OK ] SSLClientServerTest.SSLConnectTimeout (1006 ms)
[ RUN      ] SSLClientServerTest.CustomizeServerSSLCtx
test.cc:5428: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] SSLClientServerTest.CustomizeServerSSLCtx (7 ms)
[----------] 8 tests from SSLClientServerTest (1056 ms total)
```

Please let me know how can I help you debug this.

Full output: [test.txt](https://github.com/yhirose/cpp-httplib/files/14590278/test.txt)

### PR DESCRIPTION
**Pull request by opoplawski**
Fixes #1798 for cmake.  This also runs the tests in the test/ directory for cmake.

### CODE REVIEW

**Comment by yhirose** [comment]
@opoplawski thanks for the pull request.
@sum01 @jimmy-park could you review it for me?

**Review by sum01 — APPROVED** [review]
I guess technically the tests run with Cmake will no longer cross-platform since it uses the bash script. I assume no one really cares though.

LGTM, all tests passed on my machine.

**Comment by yhirose** [comment]
@opoplawski could you make an adjustment according to @jimmy-park's comment?

**Comment by opoplawski** [comment]
Hmm, for cross platform support I think the meson style approach will be needed here.  Unfortunately I don't have the time or interest for that so I'll leave that to someone else.  Hopefully you can use the `_OPENSSL_VERSION` cmake variable for checks.

**Pull request closed without merging**
