### PR TITLE
Threadpool: don't allow enqueueing after shutdown.

### PR DESCRIPTION
**Pull request by Xiaotian0726**
A threadpool should ignore all the enqueueing tasks after its shutdown rather than pushing them into the `job_` list.

### CODE REVIEW

**Comment by yhirose** [comment]
@Xiaotian0726, thanks for the pull request. Could you explain more about this change, and provide at least one unit test in `test/test/cc` for this issue? Thanks!

**Comment by Xiaotian0726** [comment]
> @Xiaotian0726, thanks for the pull request. Could you explain more about this change, and provide at least one unit test in `test/test/cc` for this issue? Thanks!

@yhirose , thanks for you reply. The explanation has been updated and a new PR of unit test is on.

**Comment by yhirose** [comment]
@Xiaotian0726, thanks for adding the unit test, however, the unit test didn't fail when I tested it with the original httplib.h without your change...

**Comment by Xiaotian0726** [comment]
> @Xiaotian0726, thanks for adding the unit test, however, the unit test didn't fail when I tested it with the original httplib.h without your change...
> 
> image

Thank you for your testing, I'll check this again later...

**Pull request closed without merging**
