### PR TITLE
Windows Crypto libs linking

### PR DESCRIPTION
**Pull request by mylogin**

### CODE REVIEW

**Comment by yhirose** [comment]
@mylogin, the changes in Makefile are ok, but I don't think the changes in httplib.h are not necessary. Please let me know why you modified httplib.h.

**Comment by mylogin** [comment]
if CPPHTTPLIB_OPENSSL_SUPPORT is not defined, then it is not necessary to link these libraries (crypt32.lib, cryptui.lib)

**Comment by yhirose** [comment]
@mylogin, thanks for the answer. Another thing that I notice is that `LIBS` includes not only liner options, but also compiler related options.

**Comment by mylogin** [comment]
git revert performed or better to do a reset last commits?

**Comment by yhirose** [comment]
@mylogin, you are right. Actually reset is better for keeping the git history clean. Thanks!

**Comment by yhirose** [comment]
Thanks for your fine contribution!

**Pull request merged**
