### PR TITLE
add to_human_string

### PR DESCRIPTION
**Pull request by stingray-11**
Adds to_human_string() for better error strings.  Some may need tweaking, I took an educated guess on a few.

### CODE REVIEW

**Comment by stingray-11** [comment]
Not sure why the windows test failed, doesn't look related to this.

**Comment by yhirose** [comment]
@stingray-11 sorry for the late reply. I don't mind to replace the existing `to_string` method with your more human readable string instead of introducing `to_human_string`. Could you make the change? Thanks!

**Comment by stingray-11** [comment]
> @stingray-11 sorry for the late reply. I don't mind to replace the existing `to_string` method with your more human readable string instead of introducing `to_human_string`. Could you make the change? Thanks!

Done!

**Comment by yhirose** [comment]
@stingray-11 thanks for your contribution!

**Pull request merged**
