### PR TITLE
support send HTTP request to Unix domain socket

### PR DESCRIPTION
**Pull request by leeyiw**
Server like Nginx could listen on Unix domain socket for HTTP requests. This commit add support for connect to Unix domain socket HTTP server by invoke Client::set_unix_socket_path(path) before any Get() or Post() action.

### CODE REVIEW

**Comment by leeyiw** [comment]
This feature request is already build and tested with Nginx/1.17.3.

**Comment by yhirose** [comment]
@leeyiw, thanks for the pull request. Could you add at least one unit text in test/test.cc to test client and server together like the following  unit test? Then, I'll start reviewing it. Thanks!

https://github.com/yhirose/cpp-httplib/blob/b251668522dd459d2c6a75c10390a11b640be708/test/test.cc#L1976-L2000

**Comment by yhirose** [comment]
@leeyiw, also it seems like the pull request supports only 'client', but not 'server' side.

**Comment by leeyiw** [comment]
> Please work on the following things:
> 
> * Add unit test cases
> * Support on server side as well

OK, I'll finish the work ASAP.

**Comment by museum-future** [comment]
Has this been merged?

**Comment by yhirose** [comment]
@leeyiw, I'll close it for now. Please let me know when the pull request is ready for review.

**Pull request closed without merging**
