### PR TITLE
Bringing Cmake back

### PR DESCRIPTION
**Pull request by sum01**
I find having Cmake support very useful, so I reverted the deletion, and fixed the issue someone had with it in #421 

Note: This PR namespaces the Cmake target, so it's now `httplib::httplib`

I also took the time to improve it in a couple ways.
* Added some Cmake options to allow for strict or relaxed dependency requirements.<sup>[1]</sup>
* Added in a way for it to properly find its (optional) dependencies for the user when `find_package(httplib)` is called so they don't have to remember to do that.
* Added a way for users to require a version in the `find_pacakge` call.<sup>[2]</sup>
* Fixed the wrong install path that was causing issue #421 
* Changed the install path to allow for end-users to change it as desired.<sup>[3]</sup>
* Added an alias target to `httplib::httplib` so people building in-tree can link against the same target as users who installed.
* Added additional compiler feature detection. This is pretty minor, just might catch a few rare failed cmake builds on old compiler versions.
* Added some documentation on all this to the README

---

[1]. Specifically the following:
- `HTTPLIB_REQUIRE_OPENSSL` (default off)
- `HTTPLIB_REQUIRE_ZLIB` (default off)
- `HTTPLIB_USE_OPENSSL_IF_AVAILABLE` (default on)
- `HTTPLIB_USE_ZLIB_IF_AVAILABLE` (default on)

[2]. I was unsure if you follow [SemVer](https://semver.org/) or not, so I made the versioning allow anything >= request version.

[3]. See [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), specifically `CMAKE_INSTALL_INCLUDEDIR`

### CODE REVIEW

**Comment by sum01** [comment]
Anything you want me to improve upon with this PR?

I think it doesn't really have any more to add to it, but I'm open to suggestions.

**Comment by yhirose** [comment]
@sum01, thank you very much for spending time for CMake support. I don't come up with any suggestion since I personally don't know much about CMake. But it looks good and complete to me.

I would like to ask you to handle the following two things before merge the PR:

1. Remove the version description (`VERSION 0.6.3`) from CMakeLIsts.txt
2. Revert the change in README

The reason why I am asking these things is to reduce necessary maintenance work as much as possible because I don't personally use it and I don't have time to support users about CMake. (That's why I removed the previous CMake support.)

When it comes to README, I would like to put only information about features and examples in README. (I have actually received similar pull requests such as #416, #408, #195. But I didn't accepted any of them with the same reason.)

I appreciate your understanding and thank you very much for your great job!

**Comment by sum01** [comment]
I'm a little bummed that you don't want the version string, as it allows specific version requirements in a `find_package` call, but very well.

As for the README, would it make sense to put that info somewhere else?
It seems odd to leave no info at all.

**Comment by sum01** [comment]
Ok I removed the version file & README changes.

The only thing that might ever need changing is the OpenSSL minimum version string, which I doubt you'll be doing often anyways.

**Comment by yhirose** [comment]
@sum01, thank you for the adjustments even if you don't fully agree with.

The OpenSSL minimum version string (1.1.1) is good with me. Also, it's actually a good idea to include the installation guide in the CMakeLists.txt file itself, so that users don't need to look around in README to find the info.

Hope it helps many users who depend on cmake. Thank you so much for the fine contribution!

**Pull request merged**
