### PR TITLE
access client certificate name in request handler

### PR DESCRIPTION
**Pull request by PixlRainbow**
update for #154 
allows request handlers to identify specific clients

### CODE REVIEW

**Comment by PixlRainbow** [comment]
about e2ecea3: I've noticed that if no client ca file is provided, the server will still start, but it will reject all clients.

**Comment by PixlRainbow** [comment]
Noticed that my PR will not compile on OpenSSL 1.1.0 as they have made some structs opaque. Will push some commits to use accessors instead soon.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the PR. I implemented what you are trying to do in a different way at https://github.com/yhirose/cpp-httplib/commit/1981e0ccad8a70524e2cbaa9ed7c2098c0207c27. In this implementation, `Request` has `const SSL* ssl` instead of `std::string X509_name`, so that users could get more information out of `SSL *`.

Here is an example to get the common name.

```cpp
    auto peer_cert = SSL_get_peer_certificate(req.ssl);
    ASSERT_TRUE(peer_cert != nullptr);

    auto subject_name = X509_get_subject_name(peer_cert);
    ASSERT_TRUE(subject_name != nullptr);

    std::string common_name;
    {
      char name[BUFSIZ];
      auto name_len = X509_NAME_get_text_by_NID(subject_name, NID_commonName,
                                                name, sizeof(name));
      common_name.assign(name, name_len);
    }

    EXPECT_EQ("Common Name", common_name);

    X509_free(peer_cert);
```

Is this approach is enough for you?

**Comment by PixlRainbow** [comment]
Yeah that works! Thanks!

**Comment by yhirose** [comment]
@PixlRainbow, thanks for your contribution!

**Pull request closed without merging**
