### PR TITLE
Fix logger never called when write_content_with_provider returns false

### LINKED ISSUE #548: The logger is never called when using ContentProvider to serve lots of data
Hello.
I've run into an issue again. When I use ContentProvider to send lots of data (see the closed #541 for the code highlight), the logger is never called because the connection seems to time out or client closes connection prematurely and `write_content_with_provider` method ends up returning false after a default 5-seconds timeout. Which makes `write_response` method exit before the logger gets called.
Here's the screenshot of the debugging session:
logger_never_called
The logger is surely set but it was never called because `write_response` exits before.

### PR DESCRIPTION
**Pull request by tsilia**
Fixes #548

### CODE REVIEW

**Comment by tsilia** [comment]
Hmm, I see the `ServerTest.SlowPost` test failed on Mac. On my Windows 10 PC this test ran OK.
Few others failed though, but they all _fail anyway, regardless of this fix_:
```
[----------] Global test environment tear-down
[==========] 122 tests from 22 test cases ran. (64748 ms total)
[  PASSED  ] 111 tests.
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] ChunkedEncodingTest.FromHTTPWatch
[  FAILED  ] ChunkedEncodingTest.WithContentReceiver
[  FAILED  ] ChunkedEncodingTest.WithResponseHandlerAndContentReceiver
[  FAILED  ] ServerTest.HeadMethod200Static
[  FAILED  ] ServerTest.GetMethodDir
[  FAILED  ] ServerTest.GetMethodDirTest
[  FAILED  ] ServerTest.GetMethodDirTestWithDoubleDots
[  FAILED  ] ServerTest.GetMethodDirMountTest
[  FAILED  ] ServerTest.GetMethodDirMountTestWithDoubleDots
[  FAILED  ] ServerTest.UserDefinedMIMETypeMapping
[  FAILED  ] MountTest.Unmount

11 FAILED TESTS
```

**Comment by yhirose** [comment]
@tsilia, looks good to me! Could you change `bRes` to `ret`?

**Comment by tsilia** [comment]
Thanks for fast response @yhirose. Force-pushed the suggested cnange.

**Comment by yhirose** [comment]
@tsilia, thanks for the update!

**Pull request merged**
