### PR TITLE
Fix #1235

### LINKED ISSUE #1235: BindIPAddress when force address family to IPV6 and set outbound interface
```
//
// Created by Kotarou on 2022/4/6.
//
#include <httplib.h>

std::unique_ptr<httplib::Client>
get_http_client(std::string_view url, int family = AF_UNSPEC, const char *nif_name = nullptr) {
    auto client = std::make_unique<httplib::Client>(url.data());

    // set outbound interface
    if (nif_name != nullptr) {
        client->set_interface(nif_name);
    }

    // set address family
    client->set_address_family(family);
    client->set_connection_timeout(5);
    client->set_read_timeout(5, 1000);
    client->set_follow_location(true);
    client->set_default_headers({{"User-Agent", "Mozilla"}});

    return client;
}

void print_response(const httplib::Result &result) {
    if (result) {
        std::cout << result->body << std::endl;
    } else {
        std::cerr << "Error: " << httplib::to_string(result.error()) << std::endl;
    }
}

int main(int argc, char *argv[]) {
    std::cout << "AF_UNSPEC, no nif" << std::endl;
    auto client = get_http_client("https://api.ip.sb:443");
    auto response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_UNSPEC, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_UNSPEC, "en0");
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET, no nif" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET);
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET, "en0");
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET6, no nif" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET6);
    response = client->Get("/ip");
    print_response(response);

    std::cout << "AF_INET6, en0" << std::endl;
    client = get_http_client("https://api.ip.sb:443", AF_INET6, "en0");
    response = client->Get("/ip");
    print_response(response);
    
    return 0;
}
```

Output:
```
AF_UNSPEC, no nif
2405:aacf:acdc:6dc:33:cda2:153e:745

AF_UNSPEC, en0
38.13.192.76

AF_INET, no nif
38.13.192.76

AF_INET, en0
38.13.192.76

AF_INET6, no nif
2405:aacf:acdc:6dc:33:cda2:153e:745

AF_INET6, en0
Error: BindIPAddress
```

not sure what cause this, but when set address family to AF_INET6 and also force to use en0 as outbound interface, library returned a bind ip error.

### PR DESCRIPTION
**Pull request by yhirose**

### CODE REVIEW

**Comment by yhirose** [comment]
@CyberKoo could you do the final test with your test code? If it works, I'll merge it and bump the version. Thanks!

**Comment by yhirose** [comment]
Somehow, `SSLClientTest.SetInterfaceWithINET6` test fails...

**Comment by CyberKoo** [comment]
it works on mac, but not on linux, I'll post more deteil later.

**Comment by CyberKoo** [comment]
When using SLAAC to obtain IPv6 address will result in the interface having more than 1 address buy only one is useable and others are deprecated.
fig1

When I run the test program, the IP address returned from if2ip is the first IP, which is deprecated and causes a connection error. You can see from the example, the preferred ipv6 address should end with 15a3, but our if2ip returns 5ffd which corresponding to the first ipv6 address.

fig2

To address this problem, the deprecated address also needs to be excluded. But there is no POSIX way to do this, this has to be done in platform-dependent way.

For Linux use the constant IFA_F_DEPRECATED defined in rtnetlink 
https://man7.org/linux/man-pages/man7/rtnetlink.7.html

For *BSD (MacOS) use macro IFA6_IS_DEPRECATED defined in in6.h (Line 448)
https://opensource.apple.com/source/xnu/xnu-1699.24.8/bsd/netinet6/in6.h

**Comment by CyberKoo** [comment]
By the way, not sure why, but after removing the if_nametoindex assignment my test code seems working now, even with a deprecated IPv6 address.

**Comment by yhirose** [comment]
> Sorry, this is incorrect should be
> 
> ```
> return !addr_candidate.empty() ? addr_candidate : std::string();
> ```
> 
> or just simply return addr_candidate;

I made the change.

> By the way, not sure why, but after removing the if_nametoindex assignment my test code seems working now, even with a > deprecated IPv6 address.

What does it mean? Don't we need the following code any more?

image

**Comment by CyberKoo** [comment]
> > Sorry, this is incorrect should be
> > ```
> > return !addr_candidate.empty() ? addr_candidate : std::string();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or just simply return addr_candidate;
> 
> I made the change.
> 
> > By the way, not sure why, but after removing the if_nametoindex assignment my test code seems working now, even with a > deprecated IPv6 address.
> 
> What does it mean? Don't we need the following code any more?
> 
> image
> 
> Please send another pull request if you find any things to be adjusted. Thanks.

Yes, maybe remove it just for now, I'll do more research about it.

**Comment by yhirose** [comment]
> Yes, maybe remove it just for now, I'll do more research about it.
I removed it.

**Pull request merged**
