### PR TITLE
Fix mulitple content length headers err

### PR DESCRIPTION
**Pull request by umbrellary**

### CODE REVIEW

**Comment by yhirose** [comment]
@umbrellary, could you provide a unit test case and explain the situation where this problem happens? Then, I'll review the pull request. Thanks!

**Comment by umbrellary** [comment]
@yhirose when Digest authentication is enabled, the problem in the picture below will occur when requesting POST.
Thanks!
image

**Comment by yhirose** [comment]
@umbrellary, thank you for the update. Could you also provide lines in httplib.h where the first 'Connection: clone' and 'Content-Length: 3' are set? Thanks!

**Comment by umbrellary** [comment]
My guess is that the client has already set it once when the server returns 401 for the first request, and it has been set again when the second request is made.
first：
image
second：
image

**Comment by yhirose** [comment]
@umbrellary, sorry but I still don't understand your comment... Could provide the except lines in httplib.h where the first 'Connection: close' and 'Content-Length: 3' are set as I requested in my previous comment? That information will tell me more insight about the problem.

**Comment by umbrellary** [comment]
Sorry, I didn't answer clearly. The two positions are highlighted in the picture below.

# 'Connection: close'

# 'Content-Length: 3'

**Comment by yhirose** [comment]
@umbrellary, thanks for your contribution!

**Pull request closed without merging**
