### PR TITLE
Added Client "Transfer-Encoding:Chunked" support when your content length is unpredictable.

### PR DESCRIPTION
**Pull request by berkanuslu**
When you're working with streams, especially if different threads control this stream, you might not know content-length, but you can transfer your data with Transfer-Encoding: Chunked. It has been implemented based on https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html documentation. I have created an example for transferring your data with chunked.

### CODE REVIEW

**Comment by yhirose** [comment]
@berkanuslu, thanks for the new pull request. It looks much simpler! Could you provide a unit test for this feature?  Then, I'll review the code. Thanks!

**Comment by evg82** [comment]
Hi @berkanuslu, Im working with your code. It works ok but have some bugs:
Content-Length is included but chunked enconding conflict with it.
gzip compresion do not work, at least in my code. The code should be very similar to the server one. It will be great if some code can be reused in server and client.

I dont know if you are working in the code or not. If the PR is enough for your needs i can continue your work.

**Comment by yhirose** [comment]
@berkanuslu, any response?

**Comment by berkanuslu** [comment]
Sorry for the late reply, folks.
@evg82 I'll check this error with gzip support. Maybe something is missing for gzip. 
@yhirose Ok, I'll add a new test code for this feature in a few days.

**Comment by berkanuslu** [comment]
I want to close this pull request and open a new one. We can continue to discuss this with the new one.

**Pull request closed without merging**
