### PR TITLE
add progress callback for http clients

### PR DESCRIPTION
**Pull request by underscorediscovery**
This is useful for displaying progress bars :) Here is how I use it.

progress

I tried to make the code idiomatic and avoided breaking any existing call sites.

```cpp
httplib::Client client(url, port);

// prints: 0 / 000 bytes => 50% complete
std::shared_ptr<httplib::Response> res = 
    cli.get("/", [](int64_t len, int64_t total) {
        printf("%lld / %lld bytes => %d%% complete\n", 
            len, total,
            (int)((len/total)*100));
    }
);
```

### CODE REVIEW

**Comment by underscorediscovery** [comment]
here is how I use it
progress

**Comment by yhirose** [comment]
@underscorediscovery, thanks for the contribution. This is truly a fantastic feature!

**Comment by underscorediscovery** [comment]
no problem @yhirose , I have some more contributions but I am still working on them. 
For the server, I have made a `listen` with non-blocking flag, and a `poll` function.  It is also minimal changes but makes it easy to use without a thread. I am still testing on more platforms before PR, and I have some other things (like websocket) I can contribute also. Thanks for the lib btw, it's a nice simple basis to use :)

**Comment by hasanenalbana** [comment]
Hi,

What is the best way to get result body from within this lambda function?

**Pull request merged**
