### PR TITLE
Improvement to multipart parser

### PR DESCRIPTION
**Pull request by mgaillard**
I noticed the parsing of multipart forms had two issues:
1. The regex would fail if attributes are not in the following order: name, filename, filename*
2. Filename* attributes are not supported

This PR is my attempt at solving the problem. I noticed two issues are related to this piece of code: #1250 and #1212.

### CODE REVIEW

**Comment by mgaillard** [comment]
I see that the build is failing because my tests are not compatible with the .h .cpp split script. I will look at it tomorrow.

**Comment by mgaillard** [comment]
When running split.py the `class MultipartFormDataParser` ends up in the httplib.cc file, which is not visible in the test.cc
For writing tests it is much easier to access directly MultipartFormDataParser instead of going through a webserver, etc.
Would it be fine to split declaration and definition of MultipartFormDataParser so that it becomes public?

**Comment by mgaillard** [comment]
I added:
```
bool parse_multipart_response(const Response &res, MultipartFormDataItems& files);
```
To allow testing the multipart form data parser without making it public.
It also allows the client code to parse multipart responses from the server.

**Comment by mgaillard** [comment]
I fixed the code so that tests pass, could I get a review?

**Comment by yhirose** [comment]
@mgaillard I fixed this issue in a simpler way. Could you try the latest httplib.h in the master branch? Thanks!

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
https://httpwg.org/specs/rfc6266.html#header.field.definition
https://www.rfc-editor.org/rfc/rfc5987.html#section-3.2
https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

**Pull request closed without merging**
