### PR TITLE
Allow to specify server IP address

### PR DESCRIPTION
**Pull request by zhenyolka**
cpp-httplib uses getaddrinfo to get server IP address to connect to. However sometimes this function might not work. For example when staticially linked with musl binary running on system. that don't have /etc/resolv.conf, android for example. Also plain DNS requests may be spoofed by ISP to block access to sites. Some Russian ISPs do that and with implementing by government National System of Domain Names this problem will grow. Also it affects privacy.
One of solution is to allow projects that use this library specify IP address of server when do HTTP/HTTPS request. So we can resolve IP over DoH/DoT or any other secure way and then pass it to cpp-httplib Client class constructor.
This pull request implements this feature.

### CODE REVIEW

**Comment by zhenyolka** [comment]
@yhirose take a look. This PR for my issue

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the excellent suggestion!
@zhenyolka, `set_hostname_addr_map(const std::map<std::string, std::string> addr_map)` looks very easy for me to understand what it tries to do instead of adding new constructors with ip. Could you adjust your code accordingly? Thanks a lot!

**Comment by zhenyolka** [comment]
@yhirose done. Could you check?

**Comment by yhirose** [comment]
@zhenyolka, thanks for the excellent contribution!

**Pull request merged**
