### PR TITLE
restore compatibility with BoringSSL

### PR DESCRIPTION
**Pull request by artpaul**
* SSLSocketStream::read was restored because client can handle partial read
* SSLSocketStream::write was rewritten with loop

### CODE REVIEW

**Comment by yhirose** [comment]
@thanks for the pull request. Could you split the commit to two commits? The first commit should be the revert of #1261, and the second one is your new change. It makes things easier for me to review. Thanks!

**Comment by artpaul** [comment]
@yhirose Done.

**Comment by yhirose** [comment]
@artpaul, I took a look at the change. It seems like the current implementation with `SSL_read_ex` and `SSL_write_ex` is much faster than this pull request (23.874s vs 35.406s) in `SSLClientServerTest.DISABLED_LargeDataTransfer`.

So I would like to enable your implementation only when `CPPHTTPLIB_NO_READ_WRITE_EX` is set. Could you make the adjustment? Thanks!

```
[master] ~/Projects/cpp-httplib/test$ time ./test --gtest_filter="*DISABLED_*" --gtest_also_run_disabled_tests
Running main() from gtest/gtest_main.cc
Note: Google Test filter = *DISABLED_*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SSLClientServerTest
[ RUN      ] SSLClientServerTest.DISABLED_LargeDataTransfer
[       OK ] SSLClientServerTest.DISABLED_LargeDataTransfer (23835 ms)
[----------] 1 test from SSLClientServerTest (23835 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (23835 ms total)
[  PASSED  ] 1 test.

real	0m23.874s
user	0m17.788s
sys	0m4.949s
```

```
[artpaul-master] ~/Projects/cpp-httplib/test$ time ./test --gtest_filter="*DISABLED_*" --gtest_also_run_disabled_tests
Running main() from gtest/gtest_main.cc
Note: Google Test filter = *DISABLED_*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SSLClientServerTest
[ RUN      ] SSLClientServerTest.DISABLED_LargeDataTransfer
[       OK ] SSLClientServerTest.DISABLED_LargeDataTransfer (35368 ms)
[----------] 1 test from SSLClientServerTest (35368 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (35368 ms total)
[  PASSED  ] 1 test.

real	0m35.406s
user	0m23.498s
sys	0m9.516s
```

**Comment by yhirose** [comment]
@artpaul, I implemented in a different way. Thanks for your contribution which helped me to fixe this issue!

**Comment by artpaul** [comment]
@yhirose Great! Thanks.

**Pull request closed without merging**
